### PR TITLE
Create storage-efs-mountfilesystem.-Ip-addr.config

### PR DESCRIPTION
**Pull request by karan6190**
Created config file for mounting EFS with an IP address.
As if due to some reasons DNS hostnames is disabled, then mounting through IP address

### CODE REVIEW

**Comment by dankhen** [comment]
Hi @karan6190 ,
Thanks for this PR. I'd like to understand a few points:
1. What's the scenario for this? When is DNS disabled? As a whole, using an IP address isn't as robust as using a DNS name. IP addresses can change and the script would fail.
2. Where should someone using your script get the IP address? You're not using a reference - you're hard-coding it into the script. That's hard to maintain.

**Comment by karan6190** [comment]
Hey dankhen, I understand your points, as fixed will not provide High availability but in some cases when you are not fully ready to alter some changes and for meanwhile need to mount EFS.

As if someone has to use this script has to create EFS and will get the IP from that. I'll sumit one more PR for creating EFS with specific IP (as depending upon the subnets range ) and will use reference in this script

**Comment by dankhen** [comment]
Sounds good. Please also make the following additional changes in this PR:
1. Call the file `storage-efs-mountfilesystem-ip-addr.config`.
1. Move the file to `elastic-beanstalk-samples/configuration-files/community-provided/instance-configuration`. This isn't an AWS-provided file.
1. Add a header with a description and your GitHub handle as the author. See example [here](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/community-provided/instance-configuration/enable-windowsupdate-dotnet.config).
1. Remove lines 3, 6, 23, 25. You never reference `FILE_SYSTEM_ID` and `REGION`.
1. Bring back the comment `Do not modify values below this line` from the original version of the file. The idea is for users of your script to only set options, and not change the script below.
1. Change the name `EFS_FILE_SYSTEM_IP` to maintain name consistency between the options (environment settings) and local script variables:
```
EFS_MOUNT_TARGET_IP=$(/opt/elasticbeanstalk/bin/get-config environment | jq -r '.MOUNT_TARGET_IP')
```

**Comment by karan6190** [comment]
Thanks Dankhen, I'll surely update the changes required and will submit the PR

**Comment by karan6190** [comment]
Hey Dankhen, as per your requested changes, I have updated the PR

**Comment by dankhen** [comment]
Thanks for the changes! Merging.

**Pull request merged**
